services:
  postgres:
    container_name: test_postgres_db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=secret_password'
      - 'POSTGRES_USER=test'
    ports:
      - '5432'